
services:
  sql-client:
    image: langfarm/paimon-flink:0.1.1
    networks:
      - langfarm_default
    command: bin/sql-client.sh
    volumes:
      - /tmp/langfarm/flink:/data
      - /tmp/langfarm/paimon:/data/paimon
      - ./scripts:/opt/flink/scripts
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager

networks:
  langfarm_default:
    external: true
