services:
  jobmanager:
    image: langfarm/paimon-flink:0.1.1
    ports:
      - "8081:8081"
    command: jobmanager
    networks:
      - langfarm_default
    volumes:
      - /tmp/langfarm/flink:/data
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        

  taskmanager:
    image: langfarm/paimon-flink:0.1.1
    depends_on:
      - jobmanager
    command: taskmanager
    networks:
      - langfarm_default
    volumes:
      - /tmp/langfarm/flink:/data
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 10


networks:
  langfarm_default:
    external: true
